### ISSUE TITLE
Moving or renaming testcases in `trustfall_core/src/resources`

### ISSUE THREAD

**Issue by ginger51011** [obi1kenobi/trustfall#141]
I noticed when I was writing my first PR that it is not completely obvious what or where the tests in `trustfall_core` are. Right now they can be found in `trustfall_core/src/resources`, but without any README this isn't at all obvious (after all, `resources` could just be a list of constants). Is there a motivation that I am missing (and if so, could it be clarified).

For me its a bit odd that test data is provided in a `src/` directory; It is not used in the final crate (as far as I know), with the exception of perhaps the schemas.

Would it make sense to move parameterized testcases to for example `trustfall_core/testcases`? Or would a README with directory structure explained in `trustfall_core` be enough? 

This is in part related to #135

**Comment by obi1kenobi** [comment]
Great point. No good-enough reason.

Once #143 merges, it's safe to move them. How about `trustfall_core/test_data`?
