### ISSUE TITLE
Add README instructions for building Python bindings on macOS M1/M2, since default macOS linter fails unless special flags are used

### ISSUE THREAD

**Issue by mwatts** [obi1kenobi/trustfall#193]
When building on macOS M2 device

rustfall/target/debug/deps/libtrustfall.dylib" "-Wl,-dead_strip" "-dynamiclib" "-Wl,-dylib" "-nodefaultlibs"
  = note: Undefined symbols for architecture arm64:
            "_PyBaseObject_Type", referenced from:
                _$LT$pyo3..pycell..PyCellBase$LT$U$GT$$u20$as$u20$pyo3..pycell..PyCellLayout$LT$T$GT$$GT$::tp_dealloc::h9586d608af4a572d in trustfall.17l279f65bojt1p2.rcgu.o
                _$LT$pyo3..types..any..PyAny$u20$as$u20$pyo3..type_object..PyTypeInfo$GT$::type_object_raw::hb694f6c9dd74ee4d in trustfall.1emd1kcdglni7bjl.rcgu.o
                _$LT$pyo3..pyclass_init..PyNativeTypeInitializer$LT$T$GT$$u20$as$u20$pyo3..pyclass_init..PyObjectInit$LT$T$GT$$GT$::into_new_object::inner::h8e7e420e01b6ac4f in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.15.rcgu.o)
            "_PyBool_Type", referenced from:
                pyo3_ffi::boolobject::PyBool_Check::h702dc831dd023420 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.4.rcgu.o)
            "_PyBytes_AsString", referenced from:
                pyo3::types::bytes::PyBytes::as_bytes::hdb139f589e41b081 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.4.rcgu.o)
            "_PyBytes_Size", referenced from:
                pyo3::types::bytes::PyBytes::as_bytes::hdb139f589e41b081 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.4.rcgu.o)
            "_PyCMethod_New", referenced from:
                pyo3_ffi::methodobject::PyCFunction_NewEx::he2d86941dd3844cb in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.14.rcgu.o)
            "_PyDict_New", referenced from:
                pyo3::types::dict::PyDict::new::h4a68695da255a2eb in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.11.rcgu.o)
            "_PyDict_Next", referenced from:
                pyo3::types::dict::PyDictIterator::next_unchecked::hbabaeb504fc2b66c in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.11.rcgu.o)
            "_PyDict_SetItem", referenced from:
                pyo3::types::dict::PyDict::set_item::haf13b1a5f5400281 in trustfall.4s4d056n71n9fb2z.rcgu.o
            "_PyErr_Fetch", referenced from:
                pyo3::err::PyErr::take::h91bcc0b49ac73ff8 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.6.rcgu.o)
            "_PyErr_GivenExceptionMatches", referenced from:
                pyo3::err::PyErr::is_instance::hb971a86ea7c949e4 in trustfall.3ukvgi2uh6rzp0ik.rcgu.o
                pyo3::err::PyErr::is_instance::h91b651685b59cba3 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.6.rcgu.o)
            "_PyErr_NewExceptionWithDoc", referenced from:
                pyo3::err::PyErr::new_type::h92f345d0567c1e6d in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.6.rcgu.o)
            "_PyErr_NormalizeException", referenced from:
                pyo3::err::PyErr::make_normalized::h919510dc34332ef2 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.6.rcgu.o)
            "_PyErr_Print", referenced from:
                pyo3::err::panic_after_error::hc3c86f48f22b60a8 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.6.rcgu.o)
            "_PyErr_PrintEx", referenced from:
                pyo3::err::PyErr::take::h91bcc0b49ac73ff8 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.6.rcgu.o)
                pyo3::err::PyErr::print::hfa7c639d34241a33 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.6.rcgu.o)
            "_PyErr_Restore", referenced from:
                pyo3::err::PyErr::restore::h85d7d64dd753e894 in trustfall.3ukvgi2uh6rzp0ik.rcgu.o
                pyo3::err::PyErr::take::h91bcc0b49ac73ff8 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.6.rcgu.o)
                pyo3::err::PyErr::restore::h15c284dd68162b74 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.6.rcgu.o)
            "_PyEval_SaveThread", referenced from:
                pyo3::gil::prepare_freethreaded_python::_$u7b$$u7b$closure$u7d$$u7d$::h6ca88f3b6f0c4383 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.13.rcgu.o)
            "_PyExc_AttributeError", referenced from:
                _$LT$pyo3..exceptions..PyAttributeError$u20$as$u20$pyo3..type_object..PyTypeInfo$GT$::type_object_raw::h4363051eb4d7356b in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.1.rcgu.o)
            "_PyExc_BaseException", referenced from:
                _$LT$pyo3..exceptions..PyBaseException$u20$as$u20$pyo3..type_object..PyTypeInfo$GT$::type_object_raw::hec1de755416a4a76 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.1.rcgu.o)
            "_PyExc_Exception", referenced from:
                _$LT$pyo3..exceptions..PyException$u20$as$u20$pyo3..type_object..PyTypeInfo$GT$::type_object_raw::h8ce1279349a475f8 in trustfall.gtfqy9r7caa3xhm.rcgu.o
            "_PyExc_ImportError", referenced from:
                _$LT$pyo3..exceptions..PyImportError$u20$as$u20$pyo3..type_object..PyTypeInfo$GT$::type_object_raw::h2fffa0495811c8c3 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.1.rcgu.o)
            "_PyExc_OverflowError", referenced from:
                _$LT$pyo3..exceptions..PyOverflowError$u20$as$u20$pyo3..type_object..PyTypeInfo$GT$::type_object_raw::h91530488decc57c5 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.1.rcgu.o)
            "_PyExc_RuntimeError", referenced from:
                _$LT$pyo3..exceptions..PyRuntimeError$u20$as$u20$pyo3..type_object..PyTypeInfo$GT$::type_object_raw::hd502a1f5d46b5b04 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.1.rcgu.o)
            "_PyExc_StopIteration", referenced from:
                _$LT$pyo3..exceptions..PyStopIteration$u20$as$u20$pyo3..type_object..PyTypeInfo$GT$::type_object_raw::haee176c325da7b41 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.1.rcgu.o)
            "_PyExc_TypeError", referenced from:
                _$LT$pyo3..exceptions..PyTypeError$u20$as$u20$pyo3..type_object..PyTypeInfo$GT$::type_object_raw::h3a44ed2896863971 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.1.rcgu.o)
            "_PyExc_ValueError", referenced from:
                _$LT$pyo3..exceptions..PyValueError$u20$as$u20$pyo3..type_object..PyTypeInfo$GT$::type_object_raw::hecfef559cf81d9f2 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.1.rcgu.o)
            "_PyException_GetCause", referenced from:
                pyo3::err::PyErr::cause::h8aa5abdcf319384c in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.6.rcgu.o)
            "_PyException_SetCause", referenced from:
                pyo3::err::PyErr::set_cause::h0fa1907376fe4443 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.6.rcgu.o)
            "_PyFloat_AsDouble", referenced from:
                pyo3::types::floatob::_$LT$impl$u20$pyo3..conversion..FromPyObject$u20$for$u20$f64$GT$::extract::ha140c8873c5fdc24 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.15.rcgu.o)
            "_PyFloat_FromDouble", referenced from:
                pyo3::types::floatob::PyFloat::new::h133f24046d48c6e5 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.15.rcgu.o)
            "_PyGILState_Ensure", referenced from:
                pyo3::gil::GILGuard::acquire_unchecked::h36b05b7f4fb364a9 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.13.rcgu.o)
            "_PyGILState_Release", referenced from:
                _$LT$pyo3..gil..GILGuard$u20$as$u20$core..ops..drop..Drop$GT$::drop::hb2034ed84068da03 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.13.rcgu.o)
            "_PyIter_Next", referenced from:
                _$LT$$RF$pyo3..types..iterator..PyIterator$u20$as$u20$core..iter..traits..iterator..Iterator$GT$::next::h76ae89cf6e6feb99 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.10.rcgu.o)
            "_PyList_Append", referenced from:
                pyo3::types::list::PyList::append::h7c8af044d87a650c in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.6.rcgu.o)
            "_PyList_New", referenced from:
                pyo3::types::list::new_from_iter::hc1f4db0b86b194dd in trustfall.2ouz77ax9rpj8bzc.rcgu.o
                pyo3::types::list::PyList::empty::h346c6931b8ece6a6 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.6.rcgu.o)
            "_PyLong_AsLong", referenced from:
                pyo3::types::num::_$LT$impl$u20$pyo3..conversion..FromPyObject$u20$for$u20$i64$GT$::extract::h1dfb245f69b5c154 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.10.rcgu.o)
            "_PyLong_FromLong", referenced from:
                pyo3::types::num::_$LT$impl$u20$pyo3..conversion..IntoPy$LT$pyo3..instance..Py$LT$pyo3..types..any..PyAny$GT$$GT$$u20$for$u20$i64$GT$::into_py::h1ad8b07343e32d9e in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.10.rcgu.o)
            "_PyLong_FromSsize_t", referenced from:
                pyo3::impl_::pyclass::get_sequence_item_from_mapping::hbdd695372d5ca4b6 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.10.rcgu.o)
                pyo3::impl_::pyclass::assign_sequence_item_from_mapping::hea89c5653a114d6c in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.10.rcgu.o)
            "_PyLong_FromUnsignedLongLong", referenced from:
                pyo3::types::num::_$LT$impl$u20$pyo3..conversion..IntoPy$LT$pyo3..instance..Py$LT$pyo3..types..any..PyAny$GT$$GT$$u20$for$u20$u64$GT$::into_py::h4b6fe5dfb4a6369b in trustfall.4onf1vwdms2whcp5.rcgu.o
            "_PyModule_Create2", referenced from:
                pyo3_ffi::modsupport::PyModule_Create::hdae666d07cad382e in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.14.rcgu.o)
            "_PyModule_GetName", referenced from:
                pyo3::types::module::PyModule::name::h01d0571523fcc3be in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.9.rcgu.o)
            "_PyNumber_Index", referenced from:
                pyo3::types::num::_$LT$impl$u20$pyo3..conversion..FromPyObject$u20$for$u20$i64$GT$::extract::h1dfb245f69b5c154 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.10.rcgu.o)
            "_PyObject_Call", referenced from:
                pyo3::instance::Py$LT$T$GT$::call_method::h4e9aa76f05caba25 in trustfall.3nzsfzrdmar54h64.rcgu.o
                pyo3::instance::Py$LT$T$GT$::call_method::h646eb32c180dc972 in trustfall.3nzsfzrdmar54h64.rcgu.o
                pyo3::instance::Py$LT$T$GT$::call_method::h8e492bdec9d76051 in trustfall.3nzsfzrdmar54h64.rcgu.o
                pyo3::instance::Py$LT$T$GT$::call_method::ha91eda28777705ac in trustfall.3nzsfzrdmar54h64.rcgu.o
                pyo3::instance::Py$LT$T$GT$::call_method::hab9e3b7553052896 in trustfall.3nzsfzrdmar54h64.rcgu.o
            "_PyObject_DelItem", referenced from:
                pyo3::impl_::pyclass::assign_sequence_item_from_mapping::hea89c5653a114d6c in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.10.rcgu.o)
            "_PyObject_Free", referenced from:
                pyo3::pyclass::PyTypeBuilder::type_doc::_$u7b$$u7b$closure$u7d$$u7d$::h3c632a3ab0154fb5 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.2.rcgu.o)
            "_PyObject_GenericGetDict", referenced from:
                pyo3::pyclass::PyTypeBuilder::finalize_methods_and_properties::hc5f365d63689bcee in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.2.rcgu.o)
            "_PyObject_GenericSetDict", referenced from:
                pyo3::pyclass::PyTypeBuilder::finalize_methods_and_properties::hc5f365d63689bcee in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.2.rcgu.o)
            "_PyObject_GetAttr", referenced from:
                pyo3::instance::Py$LT$T$GT$::getattr::h7df2f439e7aabe2e in trustfall.3nzsfzrdmar54h64.rcgu.o
                pyo3::types::any::PyAny::getattr::hb91e438047890159 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.11.rcgu.o)
            "_PyObject_GetItem", referenced from:
                pyo3::impl_::pyclass::get_sequence_item_from_mapping::hbdd695372d5ca4b6 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.10.rcgu.o)
            "_PyObject_GetIter", referenced from:
                pyo3::types::iterator::PyIterator::from_object::h5a73463bda3d58ed in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.10.rcgu.o)
            "_PyObject_IsInstance", referenced from:
                pyo3::types::any::PyAny::is_instance::hd60c14b01e266bb7 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.11.rcgu.o)
            "_PyObject_Malloc", referenced from:
                pyo3::pyclass::PyTypeBuilder::type_doc::_$u7b$$u7b$closure$u7d$$u7d$::h3c632a3ab0154fb5 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.2.rcgu.o)
            "_PyObject_Repr", referenced from:
                pyo3::types::any::PyAny::repr::h1435ed1aef043d03 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.11.rcgu.o)
            "_PyObject_SetAttr", referenced from:
                pyo3::types::any::PyAny::setattr::h001a96e9c5b2c726 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.11.rcgu.o)
                pyo3::types::any::PyAny::setattr::h3d0d6cfb23fbc0be in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.11.rcgu.o)
            "_PyObject_SetAttrString", referenced from:
                pyo3::type_object::initialize_tp_dict::h1fd98a1152ff8ce3 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.13.rcgu.o)
            "_PyObject_SetItem", referenced from:
                pyo3::impl_::pyclass::assign_sequence_item_from_mapping::hea89c5653a114d6c in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.10.rcgu.o)
            "_PyObject_Str", referenced from:
                pyo3::types::any::PyAny::str::hf10b6262f50db3de in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.11.rcgu.o)
            "_PySequence_Check", referenced from:
                pyo3::types::sequence::extract_sequence::h6e0a5594f076ea39 in trustfall.5dt418mmlhsyn78w.rcgu.o
            "_PySequence_Size", referenced from:
                pyo3::types::sequence::PySequence::len::h3f4d3812e803cb81 in trustfall.4h0hsrkv7zxyviz4.rcgu.o
            "_PyTuple_New", referenced from:
                pyo3::types::tuple::_$LT$impl$u20$pyo3..conversion..IntoPy$LT$pyo3..instance..Py$LT$pyo3..types..tuple..PyTuple$GT$$GT$$u20$for$u20$$LP$T0$C$T1$RP$$GT$::into_py::h0c856ef5570679d3 in trustfall.2l0c400p6y8unapz.rcgu.o
                pyo3::types::tuple::_$LT$impl$u20$pyo3..conversion..IntoPy$LT$pyo3..instance..Py$LT$pyo3..types..tuple..PyTuple$GT$$GT$$u20$for$u20$$LP$T0$C$$RP$$GT$::into_py::h22c5235770ba0f0c in trustfall.3euee45au1n91f8l.rcgu.o
                pyo3::types::tuple::_$LT$impl$u20$pyo3..conversion..IntoPy$LT$pyo3..instance..Py$LT$pyo3..types..tuple..PyTuple$GT$$GT$$u20$for$u20$$LP$T0$C$T1$C$T2$RP$$GT$::into_py::h968a12f2f067c08c in trustfall.4khl9kldign9qx9n.rcgu.o
                pyo3::types::tuple::_$LT$impl$u20$pyo3..conversion..IntoPy$LT$pyo3..instance..Py$LT$pyo3..types..tuple..PyTuple$GT$$GT$$u20$for$u20$$LP$T0$C$T1$C$T2$C$T3$RP$$GT$::into_py::h5d11838844370bc4 in trustfall.4khl9kldign9qx9n.rcgu.o
                pyo3::types::tuple::_$LT$impl$u20$pyo3..conversion..IntoPy$LT$pyo3..instance..Py$LT$pyo3..types..any..PyAny$GT$$GT$$u20$for$u20$$LP$T0$C$$RP$$GT$::into_py::h785392e9a657d0d0 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.10.rcgu.o)
                pyo3::types::tuple::_$LT$impl$u20$pyo3..conversion..IntoPy$LT$pyo3..instance..Py$LT$pyo3..types..any..PyAny$GT$$GT$$u20$for$u20$$LP$T0$C$$RP$$GT$::into_py::h90e4d1640c08cc3c in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.15.rcgu.o)
                pyo3::types::tuple::PyTuple::empty::h5c3bb6c72df3177f in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.14.rcgu.o)
                ...
            "_PyTuple_SetItem", referenced from:
                pyo3::types::tuple::_$LT$impl$u20$pyo3..conversion..IntoPy$LT$pyo3..instance..Py$LT$pyo3..types..tuple..PyTuple$GT$$GT$$u20$for$u20$$LP$T0$C$T1$RP$$GT$::into_py::h0c856ef5570679d3 in trustfall.2l0c400p6y8unapz.rcgu.o
                pyo3::types::tuple::_$LT$impl$u20$pyo3..conversion..IntoPy$LT$pyo3..instance..Py$LT$pyo3..types..tuple..PyTuple$GT$$GT$$u20$for$u20$$LP$T0$C$$RP$$GT$::into_py::h22c5235770ba0f0c in trustfall.3euee45au1n91f8l.rcgu.o
                pyo3::types::tuple::_$LT$impl$u20$pyo3..conversion..IntoPy$LT$pyo3..instance..Py$LT$pyo3..types..tuple..PyTuple$GT$$GT$$u20$for$u20$$LP$T0$C$T1$C$T2$RP$$GT$::into_py::h968a12f2f067c08c in trustfall.4khl9kldign9qx9n.rcgu.o
                pyo3::types::tuple::_$LT$impl$u20$pyo3..conversion..IntoPy$LT$pyo3..instance..Py$LT$pyo3..types..tuple..PyTuple$GT$$GT$$u20$for$u20$$LP$T0$C$T1$C$T2$C$T3$RP$$GT$::into_py::h5d11838844370bc4 in trustfall.4khl9kldign9qx9n.rcgu.o
                pyo3::types::tuple::_$LT$impl$u20$pyo3..conversion..IntoPy$LT$pyo3..instance..Py$LT$pyo3..types..any..PyAny$GT$$GT$$u20$for$u20$$LP$T0$C$$RP$$GT$::into_py::h785392e9a657d0d0 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.10.rcgu.o)
                pyo3::types::tuple::_$LT$impl$u20$pyo3..conversion..IntoPy$LT$pyo3..instance..Py$LT$pyo3..types..any..PyAny$GT$$GT$$u20$for$u20$$LP$T0$C$$RP$$GT$::into_py::h90e4d1640c08cc3c in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.15.rcgu.o)
                pyo3::types::tuple::_$LT$impl$u20$pyo3..conversion..IntoPy$LT$pyo3..instance..Py$LT$pyo3..types..any..PyAny$GT$$GT$$u20$for$u20$$LP$T0$C$$RP$$GT$::into_py::h7c9aa2a59a9d5ab6 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.14.rcgu.o)
                ...
            "_PyType_FromSpec", referenced from:
                pyo3::pyclass::PyTypeBuilder::build::hf4348185b05c2de9 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.2.rcgu.o)
            "_PyType_GenericAlloc", referenced from:
                _$LT$pyo3..pyclass_init..PyNativeTypeInitializer$LT$T$GT$$u20$as$u20$pyo3..pyclass_init..PyObjectInit$LT$T$GT$$GT$::into_new_object::inner::h8e7e420e01b6ac4f in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.15.rcgu.o)
            "_PyType_IsSubtype", referenced from:
                pyo3_ffi::object::PyObject_TypeCheck::he2e6a90841a167d9 in trustfall.486925zimk1r10o2.rcgu.o
            "_PyUnicode_AsEncodedString", referenced from:
                pyo3::types::string::PyString::to_string_lossy::h28183f3c4a93ef40 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.7.rcgu.o)
            "_PyUnicode_AsUTF8AndSize", referenced from:
                pyo3::types::string::PyString::to_str::h082176446f92ad12 in trustfall.pn4yh0fjcqanpr9.rcgu.o
                pyo3::types::string::PyString::to_str::h3e894380776e1e59 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.7.rcgu.o)
            "_PyUnicode_FromStringAndSize", referenced from:
                pyo3::types::string::PyString::new::h905534f740651e9b in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.7.rcgu.o)
                pyo3::types::string::PyString::intern::hde635305b74ad682 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.7.rcgu.o)
            "_PyUnicode_InternInPlace", referenced from:
                pyo3::types::string::PyString::intern::hde635305b74ad682 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.7.rcgu.o)
            "_PyUnicode_Type", referenced from:
                _$LT$pyo3..types..string..PyString$u20$as$u20$pyo3..type_object..PyTypeInfo$GT$::type_object_raw::h4a7abba80c7a7642 in trustfall.pn4yh0fjcqanpr9.rcgu.o
            "_Py_InitializeEx", referenced from:
                pyo3::gil::prepare_freethreaded_python::_$u7b$$u7b$closure$u7d$$u7d$::h6ca88f3b6f0c4383 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.13.rcgu.o)
            "_Py_IsInitialized", referenced from:
                pyo3::gil::prepare_freethreaded_python::_$u7b$$u7b$closure$u7d$$u7d$::h6ca88f3b6f0c4383 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.13.rcgu.o)
                pyo3::gil::GILGuard::acquire::_$u7b$$u7b$closure$u7d$$u7d$::h583d1722ee10348b in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.13.rcgu.o)
            "__Py_Dealloc", referenced from:
                pyo3_ffi::object::Py_DECREF::ha39a1b4c287a2638 in trustfall.486925zimk1r10o2.rcgu.o
                pyo3_ffi::object::Py_DECREF::h67c280408c78dd24 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.13.rcgu.o)
            "__Py_FalseStruct", referenced from:
                pyo3_ffi::boolobject::Py_False::hf073eb2012a9a6e4 in trustfall.4ecyax1jdkwrdpe7.rcgu.o
            "__Py_NoneStruct", referenced from:
                pyo3_ffi::object::Py_None::hcb13b7c7f8ab31fc in trustfall.486925zimk1r10o2.rcgu.o
                pyo3_ffi::object::Py_None::h4aee046fef27f159 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.13.rcgu.o)
            "__Py_TrueStruct", referenced from:
                pyo3_ffi::boolobject::Py_True::hd968c3718bcacc53 in trustfall.4ecyax1jdkwrdpe7.rcgu.o
                pyo3_ffi::boolobject::Py_True::hce21c127d0a5fc98 in libpyo3-6b558687533ac4a8.rlib(pyo3-6b558687533ac4a8.pyo3.247cb10c-cgu.4.rcgu.o)
          ld: symbol(s) not found for architecture arm64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)

error: could not compile `pytrustfall` due to previous error

**Comment by obi1kenobi** [comment]
Hi! Sorry for the inconvenience, thanks for reporting the problem. What's the build command that triggers this?

This seems like a failure to build and link `pyo3`, and this issue seems relevant: https://github.com/PyO3/pyo3/issues/1330

Make sure you're either building through `maturin` (e.g. `maturin develop`) or using the linker flags specified in that issue.

Please let me know if that worked and I can adjust our docs appropriately.

**Comment by obi1kenobi** [comment]
You should be able to put the same content in a repo-level `.cargo/config.toml` file and get the same effect without modifying global settings.

Aside from that, I'd strongly recommend trying `maturin`. I don't think I've ever run `cargo build` inside the `pytrustfall` directory — I do everything through `maturin`. It's extremely polished and has conveniences for building the bindings and installing them in the local virtualenv with a single command: https://www.maturin.rs/develop.html

**Comment by obi1kenobi** [comment]
Btw, I'd love to hear what you're building with the Python bindings, if you don't mind sharing! Definitely let me know if there's anything else I can help with.

**Comment by mwatts** [comment]
I am actually not using the Python bindings and was just working to build the entire codebase.  I may in the future but right now just looking at technology approach

**Comment by obi1kenobi** [comment]
Got it, thanks! Let me know if there's anything I can do to help in that process or any questions I can answer 👍
