### ISSUE TITLE
Hovering comments on the playground throws an error (and sometimes an overlay)

### ISSUE THREAD

**Issue by u9g** [obi1kenobi/trustfall#285]
https://play.predr.ag/hackernews , open your dev console, then hover any comment

**Comment by u9g** [comment]
When a full screen overlay is shown, this is the stack trace: 
![image](https://github.com/obi1kenobi/trustfall/assets/43508353/a0d5c79b-2e4b-4d68-84f4-24e616edefd3)
![image](https://github.com/obi1kenobi/trustfall/assets/43508353/52bb359b-40df-4d14-8570-7954f8dd668f)

**Comment by obi1kenobi** [comment]
@paavanb any idea what might be happening here?

The web playground is running a slightly older version of the code than is in the repo, but this reproduces using the local code in the repo as well:
![image](https://github.com/obi1kenobi/trustfall/assets/2348618/53af7515-80dc-4f3d-bc9b-0ce55a20dd02)
