### ISSUE TITLE
Unclear circular implementation relationship error being thrown

### ISSUE THREAD

**Issue by u9g** [obi1kenobi/trustfall#317]
Hi, with this schema, I am getting an unclear `The following types have a circular implementation relationship, which is not allowed: ["ConditionalExpression", "IfStatementOrTernary"]` error, here's the schema

https://gist.github.com/u9g/ae86313869873dbae8751fd63b77607d

I took a look back later, and made the revisions shown in the top revision here: https://gist.github.com/u9g/bec1091f0c1a19e55eee011e77de5298/revisions and now the schema works?? Not sure what's happening but definitely somethings wrong because if it was truly circular that would be incorrect too.

**Comment by obi1kenobi** [comment]
I found a few schema error edge cases that weren't being properly checked, #322 has the fix.

In the process it found a variety of issues with the schema in the gist, including the `implements` of a non-`interface` and some missing fields that are required to correctly implement some of the declared interfaces.

Lmk if you get a chance to test the new version after #322 merges.
