### ISSUE TITLE
Not valid rust error from stubgen

### ISSUE THREAD

**Issue by u9g** [obi1kenobi/trustfall#392]
Running stubgen on [this schema](https://gist.github.com/u9g/b558a6a575d0a2b0f1cdd8ed7e8b3b83) throws: 
```
thread 'main' panicked at 'not valid Rust: Error("expected expression")', /home/u9g/.cargo/registry/src/index.crates.io-6f17d22bba15001f/trustfall_stubgen-0.2.0/src/root.rs:130:70
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by obi1kenobi** [comment]
Yeah, it doesn't do any escaping yet. The schema has an edge named `type` which is a Rust keyword and causes a parse error when generating the adapter code.

I need to add escaping, but to get you unblocked in the meantime — rename the edge to `type_` and it should generate a valid adapter. Then you can keep the module name as `type_` etc. but change the edge name back.
