### ISSUE TITLE
Query accepting properties with @transform

### ISSUE THREAD

**Issue by era** [obi1kenobi/trustfall#450]
Trustfall currently doesn't support using `@transform` on properties, but we don't have a validation in-place to avoid users doing such query. For example using the [Trustfall Playground](https://play.predr.ag/hackernews#?f=2&q=*3-Latest-stories-on-HackerNews-that-have-a-minimum-score-and-karma*lquery---0Latest*9max*B-100*0---2title-*o*l--_2byUsername-*o*l--_2submittedUrl-*o*l--_2score-*o-*f*9*p-***G*e***L-*v-*c***4minScore***j*0*l--_2storyUrl*B-url-*o-*F-*T*9*p-**count***0*l*l--_2byUser---4karma-*o-*f*9*p-***G*e***L-*v-*c***4minKarma***j*0*l--_2--*0*J*l*J&v=--0**minScore***B-5*L*l--_0**minKarma***B-300*l*J) is possible to run:

```
# Latest stories on HackerNews that have a minimum score and karma
query {
  Latest(max: 100) {
    title @output
    byUsername @output
    submittedUrl @output
    score @output @filter(op: ">=", value: ["$minScore"])
    storyUrl: url @output @fold @transform(op: "count")

    byUser {
      karma @output @filter(op: ">=", value: ["$minKarma"])
    }
  }
}
```

Which returns:

```
[
  {
    "byUsername": "thunderbong",
    "karma": 54591,
    "score": 26,
    "storyUrl": "https://news.ycombinator.com/item?id=37175721",
    "submittedUrl": "https://fortomorrow.org/explore-solutions/sargablock",
    "title": "Sargablock: Bricks from Seaweed"
  }
]
```
Note that `@fold` is also not allowed on a property. So the following example should not be allowed as well:

```
# Latest stories on HackerNews that have a minimum score and karma
query {
  Latest(max: 100) {
    title @output
    byUsername @output
    submittedUrl @output
    score @output @filter(op: ">=", value: ["$minScore"])
    storyUrl: url @output @fold

    byUser {
      karma @output @filter(op: ">=", value: ["$minKarma"])
    }
  }
}
```

**Comment by obi1kenobi** [comment]
Ah, whoops! Nice catch.
