### ISSUE TITLE
Binary wheels for Python 3.12

### ISSUE THREAD

**Issue by miikka** [obi1kenobi/trustfall#649]
Hey, I was delighted to learn that Trustfall has Python bindings. However, [the version on PyPI](https://pypi.org/project/trustfall/0.1.6/#files) does not have binary wheels for Python 3.12 and is fairly old in general. Looks like building the wheels has already been set up in https://github.com/obi1kenobi/trustfall/pull/487 – maybe you could just publish a new version of the Python package?

**Comment by obi1kenobi** [comment]
Sure, let's do it! 👆 

I'd love to hear more about your Python + Trustfall use case btw!
